print(15*'-')
print('Cadastro')
print(15*'-')
nome = input('Digite seu nome: ')
email = input('Digite seu email: ')
escola = input('Digite o nome da sua escola: ')
print(15*'-')
print('Cadastro concluido')
print(15*'-')
print(f'Usuario(a): {nome}')
print(f'Email: {email}')
print(f'Escola: {escola}')